### PR TITLE
Empty messages bug repair and turn off hints (autocomplete)

### LINKED ISSUE #69: Empty messages can be sent using repeated spaces
Although an empty string is not taken into account but still repeated spaces are considered to be sent. This should not happen.

image

### PR DESCRIPTION
**Pull request by RMaster121**
This repairs bug #69 and turns chat hints (autocomplete) off.

### CODE REVIEW

**Comment by gridhead** [comment]
Please go ahead and have yourself assigned to #69 by commenting under the issue asking for an assignment. Once that issue is assigned to you, we'd get into reviewing your PR.

**Comment by RMaster121** [comment]
@t0xic0der I am assigned to this issue. Can you review this pull request?

**Review by gridhead — APPROVED** [review]
LGTM.

image

No empty messages can be sent using repeated spaces and the autocompletes have been turned off.

**Comment by gridhead** [comment]
Thank you for your contributions @RMaster121. Feel free to pick any other issue of your choice.

**Pull request merged**
