### PR TITLE
Fix issue #31: Add a "Copy to Clipboard" button for chatroom ID

### LINKED ISSUE #31: Add a *Copy to Clipboard* button for chatroom ID

### PR DESCRIPTION
**Pull request by VaibhavSaini19**

### CODE REVIEW

**Comment by gridhead** [comment]
I believe the code needs a slight reworking. I am unable to merge this due to available conflicts in the commits in your branch.

**Comment by VaibhavSaini19** [comment]
Resolved the conflicts

**Comment by gridhead** [comment]
Can you make the theme for the `COPY` button fall in line with that of the entire web app? 
Screenshot from 2020-05-26 13-12-59 
Also, we are making use of UIKit CSS framework here so feel free to read about it [here](https://getuikit.com/)

**Comment by gridhead** [comment]
Also, visibility of the button is compromised when it is hovered upon.

**Comment by gridhead** [comment]
The new changes that you have introduced through the [latest commit](https://github.com/astrosonic/sanctuary/pull/32/commits/c8469069ad1558ecb52a5ea461b18f7cb2bf71c9) some layout and functional regressions.
- The background colour of the `COPY` should be the background color of the entire site.
- The `COPIED` prompt disappears after 1 sec. I think it should stay.
- There is an irregular spacing under the `Chatroom joining ID` text. I think it is a consequence of adding that button towards right.
- Is the exclamation sign looking good? I will leave that for you to decide. :slightly_smiling_face: 
Screenshot from 2020-05-26 19-34-04

**Comment by VaibhavSaini19** [comment]
I don't have that irregular space below the 'Chatroom joining ID' text. Can you check that again?
Rest of the points have been implemented
Capture

**Comment by gridhead** [comment]
I can confirm this.

This issue is exclusive only to Firefox.
Screenshot from 2020-05-27 19-09-08

While it looks just as good in Chrome.
Screenshot from 2020-05-27 19-09-37

Let us just assume that people are more likely to use Chrome than they are to use Firefox and call this issue fixed. :wink: 

**P.S.** No. No. Not so early. The chatroom ID display on Chrome is kind of broken now due to the fact that it is aligned to *left side* when it should be *justified*.

**Comment by gridhead** [comment]
Here's my two cents on the situation. I think Chrome manages to remove the difference between the Chatroom ID title and content by sending parts of the content text below when it comes too close to the button.

Your Chrome screenshot and mine look very identical.

**Comment by VaibhavSaini19** [comment]
Figured out the issue. UIKit's css class for aligning it right was adding margin on left and bottom. Removed it and applied custom style to fix it. 
Capture

**Comment by gridhead** [comment]
Reviewed the changes. Good work. Merging. :+1:

**Pull request merged**
