### PR TITLE
Windows console fix

### LINKED ISSUE #61: Console Colors on windows do not work
I have also initiated a pull request to fix this

### PR DESCRIPTION
**Pull request by ghost**
This is a very small change (It is also cross-platform)

fixes: #61

### CODE REVIEW

**Comment by ghost** [comment]
@t0xic0der check this out

**Comment by gridhead** [comment]
Only @VaibhavSaini19 and @khallnayak are the ones who have their development environment on Windows. Feel free to add your reviews.

**Comment by ghost** [comment]
Great, It does not do much but parses ansi escape sequences which are not parsed by default

**Review by VaibhavSaini19 — CHANGES_REQUESTED** [review]
@xcodz-dot  could you please post a screenshot of how it is supposed to look? The console looks the same to me still

**Comment by ghost** [comment]
Current Output:

termn

Expected Ouput:

terme

This parses ansi escape sequences

**Review by VaibhavSaini19 — APPROVED** [review]
I see
Capture

Looks good to me

**Comment by ghost** [comment]
@t0xic0der check this out

**Comment by ghost** [comment]
@shivangswain check this PR.

**Comment by ghost** [comment]
This PR is ready to be merged, please check this @shivangswain @t0xic0der @khallnayak

**Comment by ghost** [comment]
Hello guys 😟

**Comment by gridhead** [comment]
@shivangswain Could you please check this on macOS to see if the new change brings regressions to the UNIX tty?

**Comment by VaibhavSaini19** [comment]
@t0xic0der why isn't this merged yet? I don't think it would break on macOS anyway

**Comment by gridhead** [comment]
I wanted to have this checked in any UNIX-like system. Seems like I would have to go ahead and test it by myself.

**Review by gridhead — APPROVED** [review]
The ANSI escape sequences work just the way they should.

image

LGTM.

**Comment by gridhead** [comment]
I think we can go ahead with 66.67% approval. The PR has already been delayed due to reviewers not turning up anyway.

**Comment by ghost** [comment]
the thing is that colorama is a cross-platform module which allows colors on windows also, by default windows does not parse ansi escape sequences so colorama does the work

**Pull request merged**
