### PR TITLE
Added the Ip address assignment support

### LINKED ISSUE #59: Add Option for IP Address
I have seen that this project does not allow to choose IP Address for hosting the Web Application, so i thought I can fix it.
Hence I will be getting a new pull request Up for the same.

### PR DESCRIPTION
**Pull request by ghost**
The new command line option `-i/--ip TEXT` to sanctuary.py allows you to define a value for ip address. Also you can set the ip to text `auto` for automatically getting the ip address (this works with ipv4 only).

I tested this on my laptop while I served the hostpot from android device. When i connected my laptop to android hotspot and used `--ip auto` with `-4` option, the server automatically detected my device and hosted on something like `192.168.43.218` through which i was able to open sanctuary in my android device and also other devices connected to its hotspot. this will also work if you use a network router or wifi. This specific feature named auto is tested on Windows, Ubuntu. It seems like that the auto feature is for windows users only. Note: auto is not counted as multiple features in one PR, with the addition of ip address support, auto is good to be included, it depends upon what you think.

fixes: #59

### CODE REVIEW

**Comment by ghost** [comment]
@t0xic0der @shivangswain @s-katte

**Comment by ghost** [comment]
@t0xic0der  @shivangswain @s-katte

**Comment by ghost** [comment]
No one ever replied :(

**Comment by gridhead** [comment]
Hi @xcodz-dot,

I know it has been a long while since we last attended your issues/PRs and I understand that it can be disheartening to be in such a situation. We would definitely get back to working on this at a later date, whenever we would find some time out of the tasks we are usually engaged in. Thanks for contributing. :)

**Comment by ghost** [comment]
:) I will open another PR because i deleted the fork while managing my repositories.

**Comment by ghost** [comment]
opened #76

**Pull request closed without merging**
